/* This file was generated by syncqt. */
#ifndef QT_QTQMLLINT_VERSION_H
#define QT_QTQMLLINT_VERSION_H

#define QTQMLLINT_VERSION_STR "6.3.2"

#define QTQMLLINT_VERSION 0x060302

#endif // QT_QTQMLLINT_VERSION_H
