/* This file was generated by syncqt. */
#ifndef QT_QTQMLDOM_VERSION_H
#define QT_QTQMLDOM_VERSION_H

#define QTQMLDOM_VERSION_STR "6.2.6"

#define QTQMLDOM_VERSION 0x060206

#endif // QT_QTQMLDOM_VERSION_H
