src/imports/tooling/CMakeLists.txt:qt_internal_add_qml_module(quicktooling
src/quickcontrols/material/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2materialstyleplugin
src/quickcontrols/material/impl/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2materialstyleimplplugin
src/quickcontrols/imagine/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2imaginestyleplugin
src/quickcontrols/imagine/impl/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2imaginestyleimplplugin
src/quickcontrols/ios/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2iosstyleplugin
src/quickcontrols/ios/impl/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2iosstyleimplplugin
src/quickcontrols/windows/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2windowsstyleplugin
src/quickcontrols/universal/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2universalstyleplugin
src/quickcontrols/universal/impl/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2universalstyleimplplugin
src/quickcontrols/CMakeLists.txt:qt_internal_add_qml_module(QuickControls2
src/quickcontrols/fusion/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2fusionstyleplugin
src/quickcontrols/fusion/impl/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2fusionstyleimplplugin
src/quickcontrols/basic/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2basicstyleplugin
src/quickcontrols/basic/impl/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2basicstyleimplplugin
src/quickcontrols/macos/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2macosstyleplugin
src/qmllocalstorage/CMakeLists.txt:qt_internal_add_qml_module(QmlLocalStorage
src/quickshapes/CMakeLists.txt:qt_internal_add_qml_module(QuickShapesPrivate
src/quickshapes/CMakeLists.txt.orig:qt_internal_add_qml_module(QuickShapesPrivate
src/qmlxmllistmodel/CMakeLists.txt:qt_internal_add_qml_module(QmlXmlListModel
src/effects/CMakeLists.txt:qt_internal_add_qml_module(QuickEffectsPrivate
src/quickcontrolsimpl/CMakeLists.txt:qt_internal_add_qml_module(QuickControls2Impl
src/qmltest/CMakeLists.txt:qt_internal_add_qml_module(QuickTest
src/quickcontrolstestutils/CMakeLists.txt:# hence qt_internal_add_qml_module. We use it in addition to qt_internal_add_module,
src/quickcontrolstestutils/CMakeLists.txt:qt_internal_add_qml_module(QuickControlsTestUtilsPrivate
src/quicktemplates/CMakeLists.txt:qt_internal_add_qml_module(QuickTemplates2
src/quicktemplates/CMakeLists.txt.orig:qt_internal_add_qml_module(QuickTemplates2
src/quicklayouts/CMakeLists.txt:qt_internal_add_qml_module(QuickLayouts
src/labs/settings/CMakeLists.txt:qt_internal_add_qml_module(LabsSettings
src/labs/sharedimage/CMakeLists.txt:qt_internal_add_qml_module(LabsSharedImage
src/labs/folderlistmodel/CMakeLists.txt:qt_internal_add_qml_module(LabsFolderListModel
src/labs/platform/CMakeLists.txt:qt_internal_add_qml_module(qtlabsplatformplugin
src/labs/models/CMakeLists.txt:qt_internal_add_qml_module(LabsQmlModels
src/labs/animation/CMakeLists.txt:qt_internal_add_qml_module(LabsAnimation
src/labs/wavefrontmesh/CMakeLists.txt:qt_internal_add_qml_module(LabsWavefrontMesh
src/quicknativestyle/CMakeLists.txt:qt_internal_add_qml_module(qtquickcontrols2nativestyleplugin
src/qmlmodels/CMakeLists.txt:qt_internal_add_qml_module(QmlModels
src/quick/CMakeLists.txt:qt_internal_add_qml_module(Quick
src/quick/window/CMakeLists.txt:qt_internal_add_qml_module(quickwindow
src/qml/Qt6QmlBuildInternals.cmake:    # Args used by qt_internal_add_qml_module directly, which should not be passed to any other
src/qml/Qt6QmlBuildInternals.cmake:function(qt_internal_add_qml_module target)
src/qml/Qt6QmlBuildInternals.cmake:        # If the qt_internal_add_qml_module call didn't specify a CLASS_NAME, we need to pre-compute
src/qml/Qt6QmlMacros.cmake.orig:    # qt_internal_add_qml_module() or left as a responsibility of the caller).
src/qml/Qt6QmlMacros.cmake:    # qt_internal_add_qml_module() or left as a responsibility of the caller).
src/qml/CMakeLists.txt:# qt_internal_add_qml_module() is executed because we need feature evaluation
src/qml/CMakeLists.txt:qt_internal_add_qml_module(Qml
src/qml/CMakeLists.txt:qt_internal_add_qml_module(QmlMeta
src/qml/CMakeLists.txt:# dependency manually instead of relying on qt_internal_add_qml_module logic. Same is applicable
src/qml/CMakeLists.txt.orig:# qt_internal_add_qml_module() is executed because we need feature evaluation
src/qml/CMakeLists.txt.orig:qt_internal_add_qml_module(Qml
src/qml/CMakeLists.txt.orig:qt_internal_add_qml_module(QmlMeta
src/qml/CMakeLists.txt.orig:# dependency manually instead of relying on qt_internal_add_qml_module logic. Same is applicable
src/quickdialogs/quickdialogsquickimpl/CMakeLists.txt:qt_internal_add_qml_module(QuickDialogs2QuickImpl
src/quickdialogs/quickdialogsquickimpl/CMakeLists.txt.orig:qt_internal_add_qml_module(QuickDialogs2QuickImpl
src/quickdialogs/quickdialogs/CMakeLists.txt:qt_internal_add_qml_module(QuickDialogs2
src/core/CMakeLists.txt:qt_internal_add_qml_module(QmlCore
src/particles/CMakeLists.txt:qt_internal_add_qml_module(QuickParticlesPrivate
src/particles/CMakeLists.txt.orig:qt_internal_add_qml_module(QuickParticlesPrivate
src/qmlworkerscript/CMakeLists.txt:qt_internal_add_qml_module(QmlWorkerScript
src/qmlworkerscript/CMakeLists.txt.orig:qt_internal_add_qml_module(QmlWorkerScript
tools/qmltime/CMakeLists.txt:qt_internal_add_qml_module(${target_name}
