/* This file was generated by syncqt. */
#ifndef QT_QTQUICK_VERSION_H
#define QT_QTQUICK_VERSION_H

#define QTQUICK_VERSION_STR "6.2.10"

#define QTQUICK_VERSION 0x06020A

#endif // QT_QTQUICK_VERSION_H
