/* This file was generated by syncqt. */
#ifndef QT_QTQUICK_VERSION_H
#define QT_QTQUICK_VERSION_H

#define QTQUICK_VERSION_STR "6.2.12"

#define QTQUICK_VERSION 0x06020C

#endif // QT_QTQUICK_VERSION_H
