version = 1

[[annotations]]
path = ["assets/cloud-with-snow-svgrepo-com.svg", "CloudWithSnow_generated.qml",
        "assets/cloud-svgrepo-com.svg", "Cloud_generated.qml",
        "assets/cloud-with-lightning-and-rain-svgrepo-com.svg", "CloudWithLightningAndRain_generated.qml",
        "assets/cloud-with-lightning-svgrepo-com.svg", "CloudWithLightning_generated.qml",
        "assets/cloud-with-rain-svgrepo-com.svg", "CloudWithRain_generated.qml",
        "assets/sun-svgrepo-com.svg", "Sun_generated.qml",
        "assets/sun-behind-cloud-svgrepo-com.svg", "SunBehindCloud_generated.qml",
        "assets/sun-behind-large-cloud-svgrepo-com.svg", "SunBehindLargeCloud_generated.qml",
        "assets/sun-behind-rain-cloud-svgrepo-com.svg", "SunBehindRainCloud_generated.qml",
        "assets/sun-behind-small-cloud-svgrepo-com.svg", "SunBehindSmallCloud_generated.qml"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2023 Googlefonts"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [ "assets/Europe.svg", "Europe_generated.qml" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2010 Kolja21"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = "assets/WorkSans-Regular.ttf"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2020 Wei Huang"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["assets/gear-alt-stroke.svg", "Gear_generated.qml"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2023 Framework7"
SPDX-License-Identifier = "MIT"
