SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtquickdialogs2quickimplversion.h QtQuickDialogs2QuickImplVersion QtQuickDialogs2QuickImpl 
SYNCQT.PRIVATE_HEADER_FILES = qquickdialogimplfactory_p.h qquickfiledialogdelegate_p.h qquickfiledialogimpl_p.h qquickfiledialogimpl_p_p.h qquickfolderbreadcrumbbar_p.h qquickfolderbreadcrumbbar_p_p.h qquickfolderdialogimpl_p.h qquickfolderdialogimpl_p_p.h qquickfontdialogimpl_p.h qquickfontdialogimpl_p_p.h qquickmessagedialogimpl_p.h qquickmessagedialogimpl_p_p.h qquickplatformfiledialog_p.h qquickplatformfolderdialog_p.h qquickplatformfontdialog_p.h qquickplatformmessagedialog_p.h qtquickdialogs2quickimplforeign_p.h qtquickdialogs2quickimplglobal_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
