/* This file was generated by syncqt. */
#ifndef QT_QTQMLCORE_VERSION_H
#define QT_QTQMLCORE_VERSION_H

#define QTQMLCORE_VERSION_STR "6.2.11"

#define QTQMLCORE_VERSION 0x06020B

#endif // QT_QTQMLCORE_VERSION_H
